language: android

env:
    global:
        - ADB_INSTALL_TIMEOUT=8

jdk: oraclejdk8

before_install:
    # Download SDK
    - yes | sdkmanager "tools" &>/dev/null
    - yes | sdkmanager "platform-tools" &>/dev/null
    - yes | sdkmanager "platforms;android-28" &>/dev/null
    # Download emulator
    - yes | sdkmanager "platforms;android-19" &>/dev/null
    - yes | sdkmanager "system-images;android-19;default;armeabi-v7a" &>/dev/null
    # Update remaining dependencies and accept licenses
    - yes | sdkmanager --update &>/dev/null
    - yes | sdkmanager --licenses &>/dev/null
    # Setup emulator
    - echo "no" | avdmanager create avd --force -n test -k "system-images;android-19;default;armeabi-v7a" &>/dev/null
    - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window & &>/dev/null

install:
    # Build debug and release(run proguard)
    - ./gradlew clean ktlintCheck assemble assembleDebugAndroidTest -Pci -s

before_script:
    # Make sure the emulator is available
    - android-wait-for-emulator

    # Turn off animations
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &

    # Wake up
    - adb shell input keyevent 82 &

script:
    # Run all checks
    - ./gradlew testDebug connectedDebugAndroidTest -Pci -s

after_success: config/deploy-apk.sh

sudo: false

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache
